apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file ./guacamole.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: guac-init
  name: guac-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guac-init
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --file ./guacamole.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: guac-init
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - " if [ ! -f /init/initdb.sql ]; then\n  echo 'initdb.sql not found, generating...';\n  /opt/guacamole/bin/initdb.sh --mysql > /init/initdb.sql;\n  echo 'initdb.sql generated.';\nelse\n  echo 'initdb.sql already exists, skipping generation.';\nfi; echo 'Keeping the init container running...'; while true; do sleep 60; done; "
          image: guacamole/guacamole:1.5.5
          livenessProbe:
            exec:
              command:
                - '[ -f /init/initdb.sql ] || exit 1'
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 10
          name: guac-init
          volumeMounts:
            - mountPath: /init
              name: guacamole-mysql-init
      restartPolicy: Always
      volumes:
        - name: guacamole-mysql-init
          persistentVolumeClaim:
            claimName: guacamole-mysql-init
