apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file ./guacamole.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: guacd
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacd
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --file ./guacamole.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: guacd
    spec:
      containers:
        - image: guacamole/guacd:1.5.5
          name: guacd
      restartPolicy: Always
