apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: guacamole-mysql-init
  name: guacamole-mysql-init
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
