apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: guacamole-config
  name: guacamole-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
