apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --file ./guacamole.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --file ./guacamole.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: CONFENV
              valueFrom:
                configMapKeyRef:
                  key: CONFENV
                  name: config-env
            - name: GENENV
              valueFrom:
                configMapKeyRef:
                  key: GENENV
                  name: setup-env
            - name: LDAP_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: LDAP_HOSTNAME
                  name: config-env
            - name: LDAP_SEARCH_BIND_DN
              valueFrom:
                configMapKeyRef:
                  key: LDAP_SEARCH_BIND_DN
                  name: config-env
            - name: LDAP_USER_BASE_DN
              valueFrom:
                configMapKeyRef:
                  key: LDAP_USER_BASE_DN
                  name: config-env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: config-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: setup-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: setup-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: config-env
          image: mysql:8.4
          livenessProbe:
            exec:
              command:
                - mysqladmin ping -h localhost -u root -p || exit 1
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: guacamole-mysql-data
            - mountPath: /docker-entrypoint-initdb.d
              name: guacamole-mysql-init
      restartPolicy: Always
      volumes:
        - name: guacamole-mysql-data
          persistentVolumeClaim:
            claimName: guacamole-mysql-data
        - name: guacamole-mysql-init
          persistentVolumeClaim:
            claimName: guacamole-mysql-init
