apiVersion: v1
data:
  GENENV: "0.1"
  MYSQL_PASSWORD: guacamole_password
  MYSQL_ROOT_PASSWORD: root_password
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: guacamole-setup-env
  name: setup-env
